version: '3.3'

services:
  app:
    build: .
    container_name: resolapp
    environment:
      - NODE_ENV=production
      - HTTP_PORT=${HTTP_PORT:-3333}
    ports:
      - "${HTTP_PORT}:3333"
    env_file:
      - .env
    restart: always
